import "../../packages/lake/src/assets/fonts/Inter.css";
import "../../packages/lake/src/assets/fonts/InterCard.css";
import "../../packages/lake/src/assets/fonts/RobotoMono.css";
import "../../packages/lake/src/assets/main.css";
import "./index.css";

import React from "react";
import ReactDOM from "react-dom/client";
import { renderToStaticMarkup } from "react-dom/server";
import { AccountStatement } from "../../packages/shared-business/src/components/AccountStatement";
import { AccountStatementFooter } from "../../packages/shared-business/src/components/AccountStatementFooter";
import { AccountStatementHeader } from "../../packages/shared-business/src/components/AccountStatementHeader";

declare global {
  interface Window {
    headerTemplate: string;
    footerTemplate: string;
  }
}

const data = {
  version: "v1",
  templateDataType: "CreditStatement",
  language: "fr",
  accountHolderName: "Jean Dupont",
  accountHolderAddress: {
    addressLine1: "2 rue de la Paix",
    street: "1 rue de la Paix",
    city: "75002 Paris",
    country: "FRA",
  },
  iban: "1234567890",
  bic: "ABCD",
  openingDate: "01/04/2024",
  closingDate: "30/04/2024",
  openingBalance: { value: "2000", currency: "EUR" },
  transactions: [
    {
      id: "1",
      label: "Sport subscription",
      date: "01/01/2025",
      type: "Card",
      credit: { value: "303.50", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "2",
      label: "Ikea",
      date: "10/01/2025",
      type: "Fees",
      credit: undefined,
      debit: { value: "200.00", currency: "EUR" },
    },
    {
      id: "3",
      label: "Loan repayment",
      date: "24/02/2025",
      type: "InternationalDirectDebit",
      credit: undefined,
      debit: { value: "1006.59", currency: "EUR" },
    },
    {
      id: "4",
      label: "Pet supplies",
      date: "12/03/2025",
      type: "SepaCreditTransfer",
      credit: { value: "322.08", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "5",
      label: "Hotel",
      date: "21/03/2025",
      type: "SepaCreditTransfer",
      credit: { value: "490.76", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "6",
      label: "Medical expenses",
      date: "08/01/2025",
      type: "SepaDirectDebit",
      credit: { value: "754.90", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "7",
      label: "Flight ticket",
      date: "05/01/2025",
      type: "Card",
      credit: undefined,
      debit: { value: "127.96", currency: "EUR" },
    },
    {
      id: "8",
      label: "Gift received",
      date: "02/02/2025",
      type: "Fees",
      credit: { value: "121.97", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "9",
      label: "Flight ticket",
      date: "25/02/2025",
      type: "InternationalDirectDebit",
      credit: { value: "1405.26", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "10",
      label: "Gas station",
      date: "24/01/2025",
      type: "SepaCreditTransfer",
      credit: { value: "1122.84", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "11",
      label: "Electricity bill",
      date: "18/02/2025",
      type: "SepaDirectDebit",
      credit: { value: "738.35", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "12",
      label: "Medical expenses",
      date: "06/03/2025",
      type: "InternationalDirectDebit",
      credit: undefined,
      debit: { value: "331.48", currency: "EUR" },
    },
    {
      id: "13",
      label: "Hotel",
      date: "27/03/2025",
      type: "SepaCreditTransfer",
      credit: undefined,
      debit: { value: "1008.68", currency: "EUR" },
    },
    {
      id: "14",
      label: "Movie ticket",
      date: "16/03/2025",
      type: "InternationalCreditTransfer",
      credit: { value: "820.54", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "15",
      label: "Restaurant",
      date: "28/02/2025",
      type: "InternationalDirectDebit",
      credit: { value: "205.97", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "16",
      label: "Flight ticket",
      date: "19/02/2025",
      type: "Fees",
      credit: { value: "306.71", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "17",
      label: "Pet supplies",
      date: "21/02/2025",
      type: "Fees",
      credit: { value: "318.83", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "18",
      label: "Medical expenses",
      date: "15/02/2025",
      type: "SepaDirectDebit",
      credit: { value: "908.53", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "19",
      label: "Medical expenses",
      date: "01/01/2025",
      type: "Fees",
      credit: { value: "306.32", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "20",
      label: "Medical expenses",
      date: "29/03/2025",
      type: "SepaDirectDebit",
      credit: { value: "321.39", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "21",
      label: "Water bill",
      date: "07/01/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "459.71", currency: "EUR" },
    },
    {
      id: "22",
      label: "Insurance refund",
      date: "02/01/2025",
      type: "Fees",
      credit: undefined,
      debit: { value: "369.40", currency: "EUR" },
    },
    {
      id: "23",
      label: "Public transport",
      date: "05/02/2025",
      type: "InternationalDirectDebit",
      credit: { value: "1212.65", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "24",
      label: "Bookstore",
      date: "03/01/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "912.65", currency: "EUR" },
    },
    {
      id: "25",
      label: "Online shopping",
      date: "15/02/2025",
      type: "Card",
      credit: { value: "1372.60", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "26",
      label: "Loan repayment",
      date: "31/03/2025",
      type: "Fees",
      credit: undefined,
      debit: { value: "770.07", currency: "EUR" },
    },
    {
      id: "27",
      label: "Public transport",
      date: "13/02/2025",
      type: "SepaDirectDebit",
      credit: { value: "1129.40", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "28",
      label: "Movie ticket",
      date: "21/02/2025",
      type: "SepaCreditTransfer",
      credit: undefined,
      debit: { value: "1326.92", currency: "EUR" },
    },
    {
      id: "29",
      label: "Water bill",
      date: "14/03/2025",
      type: "Fees",
      credit: undefined,
      debit: { value: "760.94", currency: "EUR" },
    },
    {
      id: "30",
      label: "Hotel",
      date: "13/02/2025",
      type: "InternationalDirectDebit",
      credit: { value: "306.71", currency: "EUR" },
      debit: { value: "274.37", currency: "EUR" },
    },
    {
      id: "31",
      label: "Restaurant",
      date: "16/03/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "694.41", currency: "EUR" },
    },
    {
      id: "32",
      label: "Pet supplies",
      date: "24/03/2025",
      type: "Card",
      credit: undefined,
      debit: { value: "335.11", currency: "EUR" },
    },
    {
      id: "33",
      label: "Medical expenses",
      date: "28/03/2025",
      type: "SepaCreditTransfer",
      credit: { value: "758.83", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "34",
      label: "Pet supplies",
      date: "12/03/2025",
      type: "SepaDirectDebit",
      credit: { value: "1210.63", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "35",
      label: "Water bill",
      date: "29/03/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "1171.04", currency: "EUR" },
    },
    {
      id: "36",
      label: "Hotel",
      date: "07/02/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: undefined,
    },
    {
      id: "37",
      label: "Loan repayment",
      date: "23/03/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "1231.22", currency: "EUR" },
    },
    {
      id: "38",
      label: "Restaurant",
      date: "11/03/2025",
      type: "Fees",
      credit: { value: "186.98", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "39",
      label: "Online shopping",
      date: "21/01/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: undefined,
    },
    {
      id: "40",
      label: "Groceries",
      date: "11/01/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "10.75", currency: "EUR" },
    },
    {
      id: "41",
      label: "Online shopping",
      date: "06/01/2025",
      type: "InternationalDirectDebit",
      credit: undefined,
      debit: undefined,
    },
    {
      id: "42",
      label: "Freelance income",
      date: "04/03/2025",
      type: "SepaDirectDebit",
      credit: { value: "39.72", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "43",
      label: "Hotel",
      date: "07/03/2025",
      type: "Fees",
      credit: undefined,
      debit: { value: "970.20", currency: "EUR" },
    },
    {
      id: "44",
      label: "Groceries",
      date: "02/01/2025",
      type: "InternationalDirectDebit",
      credit: { value: "542.21", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "45",
      label: "Pet supplies",
      date: "19/01/2025",
      type: "Card",
      credit: { value: "266.02", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "46",
      label: "Freelance income",
      date: "14/03/2025",
      type: "SepaCreditTransfer",
      credit: undefined,
      debit: { value: "983.87", currency: "EUR" },
    },
    {
      id: "47",
      label: "Groceries",
      date: "20/01/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "832.10", currency: "EUR" },
    },
    {
      id: "48",
      label: "Loan repayment",
      date: "07/02/2025",
      type: "Card",
      credit: undefined,
      debit: { value: "1244.48", currency: "EUR" },
    },
    {
      id: "49",
      label: "Bookstore",
      date: "30/03/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "79.76", currency: "EUR" },
    },
    {
      id: "50",
      label: "Hotel",
      date: "23/03/2025",
      type: "SepaDirectDebit",
      credit: undefined,
      debit: { value: "1262.17", currency: "EUR" },
    },
    {
      id: "51",
      label: "Concert",
      date: "11/03/2025",
      type: "SepaCreditTransfer",
      credit: undefined,
      debit: { value: "277.51", currency: "EUR" },
    },
    {
      id: "52",
      label: "Concert",
      date: "04/03/2025",
      type: "InternationalDirectDebit",
      credit: { value: "534.40", currency: "EUR" },
      debit: undefined,
    },
    {
      id: "53",
      label: "Concert",
      date: "04/03/2025",
      type: "Credit Transfer",
      credit: { value: "500.40", currency: "EUR" },
      debit: undefined,
    },
  ],
  feesDebit: { value: "10", currency: "EUR" },
  feesCredit: { value: "5", currency: "EUR" },
  totalsCredit: { value: "400", currency: "EUR" },
  totalsDebit: { value: "600", currency: "EUR" },
  closingBalance: { value: "1800", currency: "EUR" },
};

// Set data on window (accessible from browser console or other scripts)
window.headerTemplate = renderToStaticMarkup(<AccountStatementHeader language={"fr"} />);

window.footerTemplate = renderToStaticMarkup(<AccountStatementFooter language={"fr"} />);

const rootElement = document.getElementById("root");
if (rootElement) {
  ReactDOM.createRoot(rootElement).render(
    <React.StrictMode>
      <div>
        {/* @ts-expect-error */}
        <AccountStatement {...data} version="v1" hideFooter={true} hideHeader={true} />
      </div>
    </React.StrictMode>,
  );
} else {
  throw new Error("Root element not found");
}
