import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { LakeHeading } from "../src/components/LakeHeading";
import { Space } from "../src/components/Space";
import { colors } from "../src/constants/design";
import { StoryBlock, StoryPart } from "./_StoriesComponents";
export default {
    title: "Typography/Heading",
    component: LakeHeading,
};
export const Variations = () => {
    return (_jsxs(StoryBlock, { title: "Text", children: [_jsxs(StoryPart, { title: "Variations", children: [_jsx(LakeHeading, { level: 1, variant: "h1", children: "Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 16 }), _jsx(LakeHeading, { level: 2, variant: "h2", children: "Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 16 }), _jsx(LakeHeading, { level: 3, variant: "h3", children: "Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 16 }), _jsx(LakeHeading, { level: 4, variant: "h4", children: "Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 16 }), _jsx(LakeHeading, { level: 5, variant: "h5", children: "Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 16 }), _jsx(LakeHeading, { level: 6, variant: "h6", children: "Lorem ipsum dolor sit amet" })] }), _jsxs(StoryPart, { title: "Colors", children: [_jsx(LakeHeading, { level: 4, variant: "h4", color: colors.gray.primary, children: "gray: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.live.primary, children: "live: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.sandbox.primary, children: "sandbox: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.positive.primary, children: "positive: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.warning.primary, children: "warning: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.negative.primary, children: "negative: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.current.primary, children: "current: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.partner.primary, children: "partner: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.swan.primary, children: "swan: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.shakespear.primary, children: "shakespear: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.darkPink.primary, children: "darkPink: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.sunglow.primary, children: "sunglow: Lorem ipsum dolor sit amet" }), _jsx(Space, { height: 8 }), _jsx(LakeHeading, { level: 4, variant: "h4", color: colors.mediumSladeBlue.primary, children: "mediumSladeBlue: Lorem ipsum dolor sit amet" })] })] }));
};
