name: Prerelease

on:
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Prerelease
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'prerelease-v') }}
    env:
      CHANGELOG: ${{ github.event.pull_request.body }}
      GH_TOKEN: ${{ github.token }}
      REF_BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Check licenses
        run: yarn license-check

      - name: Build
        run: yarn build

      - name: Get version
        id: version
        run: echo version="$REF_BRANCH" | sed -e 's/prerelease-//g' >> $GITHUB_OUTPUT

      - name: Create GitHub prerelease
        run: gh release create ${{ steps.version.outputs.version }} --title ${{ steps.version.outputs.version }} --notes "$CHANGELOG" --prerelease

      - name: Variables inspect
        run: |
          echo ${{ steps.version.outputs.version }}
          echo "$CHANGELOG"

      # - name: Publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      #     yarn workspace @swan-io/lake publish --tag next
      #     yarn workspace @swan-io/shared-business publish --tag next

      # - name: Notify on Slack
      #   uses: bloodyowl/slack-message-release-action@v1.1.5
      #   with:
      #     version: ${{ steps.version.outputs.version }}
      #     changelog: "$CHANGELOG"
      #     slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
